# Generated by Django 4.1.5 on 2023-05-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woow', '0004_remove_post_month_post_url_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['title', 'body'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='address',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=2, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
